### PR TITLE
do MySQL syntax right (sigh)

### PR DESCRIPTION
**Pull request by stevan**
Sorry, needs this one too

### CODE REVIEW

**Comment by stevan** [comment]
Refs #5

**Comment by vti** [comment]
Thank you!

**Comment by stevan** [comment]
Any way we can get this released to CPAN soon? Do you need any help to do that?

**Comment by vti** [comment]
Did i merge everything? I can release any time.

**Comment by stevan** [comment]
Yes, everything looks to be merged.

**Pull request merged**
